#!/usr/bin/env python3
"""Test-only cryptography/OpenSSL oracle, never a crate/runtime dependency."""
from pathlib import Path
import cryptography
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
rows=[f'// Generated by tools/aead_vectors.py with cryptography {cryptography.__version__}.','&[']
for seed in [0,1,255]:
    key=bytes((i*11+seed)&255 for i in range(32))
    nonce=bytes((i*17+seed)&255 for i in range(12))
    for a in [0,1,15,16,17,32,33]:
        for n in [0,1,15,16,17,63,64,65,129,1024,1025]:
            aad=bytes((i*13+seed)&255 for i in range(a))
            plain=bytes((i*7+seed)&255 for i in range(n))
            out=ChaCha20Poly1305(key).encrypt(nonce,plain,aad)
            rows.append(f'    ({seed}usize,{a}usize,{n}usize,"{out[:-16].hex()}","{out[-16:].hex()}"),')
rows.append(']')
(Path(__file__).resolve().parents[1]/'tests/aead_vectors.in').write_text('\n'.join(rows)+'\n')
