#!/usr/bin/env python3
"""Independent test-only cryptography/OpenSSL oracle; never a Cargo dependency."""
from pathlib import Path
import cryptography
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
root=Path(__file__).resolve().parents[1]
rows=[f'// cryptography {cryptography.__version__}; generated by tools/aes_vectors.py','&[']
for seed in range(256):
 key=bytes((i*11+seed)&255 for i in range(16))
 plain=bytes((i*7+seed*3)&255 for i in range(16))
 cipher=Cipher(algorithms.AES(key),modes.ECB()).encryptor()
 out=cipher.update(plain)+cipher.finalize()
 rows.append(f'({seed}usize,"{out.hex()}"),')
rows.append(']');(root/'tests/aes_vectors.in').write_text('\n'.join(rows)+'\n')
rows=[f'// cryptography {cryptography.__version__}; generated by tools/aes_vectors.py','&[']
for seed in [0,1,255]:
 key=bytes((i*11+seed)&255 for i in range(16));nonce=bytes((i*17+seed)&255 for i in range(12))
 for a in [0,1,15,16,17,32,33]:
  for n in [0,1,15,16,17,31,32,33,129,1024,1025]:
   aad=bytes((i*13+seed)&255 for i in range(a));plain=bytes((i*7+seed)&255 for i in range(n))
   out=AESGCM(key).encrypt(nonce,plain,aad)
   rows.append(f'({seed}usize,{a}usize,{n}usize,"{out[:-16].hex()}","{out[-16:].hex()}"),')
rows.append(']');(root/'tests/aes_gcm_vectors.in').write_text('\n'.join(rows)+'\n')
