#!/usr/bin/env python3
"""Independent arbitrary-precision test oracle; no production dependency."""
from pathlib import Path

def tag(key, message):
    r = int.from_bytes(key[:16], 'little') & 0x0ffffffc0ffffffc0ffffffc0fffffff
    h = 0
    for at in range(0, len(message), 16):
        n = int.from_bytes(message[at:at+16] + b'\x01', 'little')
        h = ((h+n)*r) % ((1 << 130)-5)
    return ((h+int.from_bytes(key[16:], 'little')) % (1 << 128)).to_bytes(16, 'little')

if __name__ == '__main__':
    rows = ['// Generated by tools/poly1305_vectors.py using Python integer arithmetic.', '&[']
    for seed in [0, 1, 127, 255, 256]:
        for length in list(range(34)) + [63,64,65,127,128,129,255,256,257,1023,1024,4096,4097]:
            key = bytes([255]*32) if seed == 256 else bytes((seed*19+i*11)&255 for i in range(32))
            message = bytes([255]*length) if seed == 256 else bytes((i*37+seed)&255 for i in range(length))
            rows.append(f'    ({seed}usize, {length}usize, "{tag(key,message).hex()}"),')
    rows.append(']')
    (Path(__file__).resolve().parents[1]/'tests/poly1305_vectors.in').write_text('\n'.join(rows)+'\n')
